import type { NextPage } from 'next';
import Head from 'next/head';
import React, { ReactElement } from 'react';
import VimLayout from '../components/layouts/vim/VimLayout';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>John Pham</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Hello</div>
    </div>
  );
};

export default Home;
